[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[vim]
source = "regex"
regex = "7\\.3\\.\\d+"
url = "http://ftp.vim.org/pub/vim/patches/7.3/"

[google-chrome]
source = "cmd"
cmd = '''wget -qO- http://dl.google.com/linux/chrome/rpm/stable/x86_64/repodata/other.xml.gz | zgrep -A1 "google-chrome-stable" | awk -F\" '/version/ {print $4"-"$6}' '''

[fbcat]
source = "aur"

[winterpy]
source = "github"
github = "lilydjwg/winterpy"

[nvchecker]
source = "github"
github = "lilydjwg/nvchecker"

[PySide]
source = "pypi"
pypi = "PySide"

[test]
source = "manual"
manual = "0.1"

["Sparkle Test App"]
source = "sparkle"
sparkle = "https://sparkle-project.org/files/sparkletestcast.xml"
