version: 2
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build image
          command: |
            make build
            docker tag wastrachan/nvchecker:latest ghcr.io/wastrachan/nvchecker:latest

      - run:
          name: Publish image
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
            echo "$GITHUB_PAT" | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
            make push
            make push REGISTRY=ghcr.io

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: Docker
          filters:
            branches:
              only: master
