version: 2
jobs:
  build:
    environment:
      REPO_NAME: "wastrachan"
      IMAGE_NAME: "nvchecker"
      IMAGE_VERSION: "2.9"
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build image
          command: |
            docker build --build-arg NVCHECKER_VERSION=$IMAGE_VERSION -t $IMAGE_NAME .
            docker tag $IMAGE_NAME $REPO_NAME/$IMAGE_NAME:$IMAGE_VERSION
            docker tag $IMAGE_NAME $REPO_NAME/$IMAGE_NAME:latest
      - deploy:
          name: publish image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push $REPO_NAME/$IMAGE_NAME:$IMAGE_VERSION
              docker push $REPO_NAME/$IMAGE_NAME:latest
            fi

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only: master
