version: 2.1

jobs:
  build:
    environment:
      IMAGE_NAME: wastrachan/nvchecker
      IMAGE_VERSION: "2.13.1"
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build image
          command: |
            docker build -t $IMAGE_NAME .
            docker tag $IMAGE_NAME $IMAGE_NAME:latest
            docker tag $IMAGE_NAME $IMAGE_NAME:$IMAGE_VERSION
      - run:
          name: Publish image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push $IMAGE_NAME:latest
              docker push $IMAGE_NAME:$IMAGE_VERSION
            fi

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              only: master
